server:
  port: 8090
  address: 0.0.0.0
  http2:
    enabled: false

lavalink:
  server:
    password: "youshallnotpass"
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    keepAliveTimeout: 30
    gcDuration: 30
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      http: true
      local: false
    plugins:
      - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.3"
        repository: "https://maven.lavalink.dev/releases"
        snapshot: false

plugins:
  youtube:
    enabled: true
    oauth:
      enabled: false
      allowSearch: true
      token: ""

metrics:
  prometheus:
    enabled: false

sentry:
  enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO
    com.sedmelluq: INFO
    dev.lavalink.youtube: DEBUG
