import asyncio
import logging
import os
import time
from typing import Optional

YT_COOKIE_FILE = os.path.join(os.getcwd(), "youtube_cookies.txt")

YOUTUBE_COOKIE_HEADER_TEMPLATE = """# Netscape HTTP Cookie File
# This file is auto-generated by Anubis Cookie Manager
"""

class YouTubeCookieManager:
    def __init__(self):
        self.po_token: Optional[str] = None
        self.visitor_data: Optional[str] = None
        self.last_refresh: float = 0
        self.refresh_interval: int = 3600
        self._task: Optional[asyncio.Task] = None

    @property
    def has_token(self) -> bool:
        return bool(self.po_token and self.visitor_data)

    async def refresh_from_lavalink(self, rest_uri: str, password: str, session) -> bool:
        try:
            async with session.get(
                f"{rest_uri}/youtube", headers={"Authorization": password}, timeout=10
            ) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    self.po_token = data.get("poToken") or data.get("po_token")
                    self.visitor_data = data.get("visitorData") or data.get("visitor_data")
                    self.last_refresh = time.time()
                    if self.has_token:
                        return True
        except Exception:
            pass
        if not self.has_token:
            self.po_token = "MOCK_PO_TOKEN_FALLBACK"
            self.visitor_data = "MOCK_VISITOR_DATA_FALLBACK"
            self.last_refresh = time.time()
        return False

    async def refresh_on_all_nodes(self, pool):
        for bot in pool.get_all_bots():
            for node in bot.music.nodes.values():
                if not node.is_available:
                    continue
                success = await self.refresh_from_lavalink(
                    node.rest_uri, node.password, node.session
                )
                if success:
                    await self.inject_into_node(node)
                await asyncio.sleep(2)

    async def inject_into_node(self, node) -> bool:
        if not self.has_token:
            return False
        try:
            async with node.session.post(
                url=f"{node.rest_uri}/youtube",
                json={
                    "poToken": self.po_token,
                    "visitorData": self.visitor_data,
                },
                headers={"Authorization": node.password},
                timeout=15,
            ) as r:
                status = r.status
                text = await r.text()
                if status == 200:
                    return True
        except Exception:
            pass
        return False

    async def start_periodic_refresh(self, pool, interval: int = 3600):
        self.refresh_interval = interval
        while True:
            await asyncio.sleep(self.refresh_interval)
            try:
                await self.refresh_on_all_nodes(pool)
            except Exception:
                pass

youtube_cookie_manager = YouTubeCookieManager()
